<?php
/**
 * Intelligence API Client - Quick Deploy Script
 * 
 * Deploys API client and bot commands on client applications
 * Run this on each client server: jcepnzzkmj, dvaxgvsxmz, fhrehrpjmu
 * 
 * Usage:
 *   php deploy_intelligence_client.php --server=jcepnzzkmj --api-key=staff_api_key_2025
 * 
 * @package Intelligence_Deployment
 * @version 1.0.0
 */

// Configuration for each server
$SERVER_CONFIGS = [
    'jcepnzzkmj' => [
        'name' => 'CIS Staff Portal',
        'domain' => 'staff.vapeshed.co.nz',
        'path' => '/home/master/applications/jcepnzzkmj/public_html',
        'api_key' => 'staff_api_key_2025'
    ],
    'dvaxgvsxmz' => [
        'name' => 'Vape Shed Retail',
        'domain' => 'vapeshed.co.nz',
        'path' => '/home/master/applications/dvaxgvsxmz/public_html',
        'api_key' => 'retail_api_key_2025'
    ],
    'fhrehrpjmu' => [
        'name' => 'Ecigdis Wholesale',
        'domain' => 'ecigdis.co.nz',
        'path' => '/home/master/applications/fhrehrpjmu/public_html',
        'api_key' => 'wholesale_api_key_2025'
    ]
];

// Parse CLI arguments
$options = getopt('', ['server:', 'api-key:', 'help']);

if (isset($options['help']) || !isset($options['server'])) {
    echo <<<HELP

Intelligence API Client Deployment
===================================

Usage:
  php deploy_intelligence_client.php --server=SERVER_ID [--api-key=KEY]

Options:
  --server=ID      Server ID (jcepnzzkmj, dvaxgvsxmz, fhrehrpjmu)
  --api-key=KEY    API key (optional, uses default from config)
  --help           Show this help

Examples:
  php deploy_intelligence_client.php --server=jcepnzzkmj
  php deploy_intelligence_client.php --server=dvaxgvsxmz --api-key=custom_key

HELP;
    exit(0);
}

$server = $options['server'];
if (!isset($SERVER_CONFIGS[$server])) {
    echo "❌ Unknown server: $server\n";
    echo "Available: " . implode(', ', array_keys($SERVER_CONFIGS)) . "\n";
    exit(1);
}

$config = $SERVER_CONFIGS[$server];
$api_key = $options['api-key'] ?? $config['api_key'];

echo "🚀 Deploying Intelligence API Client\n";
echo "   Server: {$config['name']} ($server)\n";
echo "   Domain: {$config['domain']}\n";
echo str_repeat('=', 60) . "\n\n";

// Step 1: Create _kb directory
$kb_dir = $config['path'] . '/_kb';
if (!is_dir($kb_dir)) {
    if (!mkdir($kb_dir, 0755, true)) {
        echo "❌ Failed to create _kb directory: $kb_dir\n";
        echo "   Check permissions for {$config['path']}\n";
        exit(1);
    }
    echo "✅ Created _kb directory\n";
} else {
    echo "ℹ️  _kb directory already exists\n";
}

// Step 2: Copy API client library
$client_source = __DIR__ . '/IntelligenceAPIClient.php';
$client_dest = $kb_dir . '/IntelligenceAPIClient.php';

if (!file_exists($client_source)) {
    echo "❌ API client library not found: $client_source\n";
    echo "   Please ensure IntelligenceAPIClient.php is in the same directory\n";
    exit(1);
}

if (!copy($client_source, $client_dest)) {
    echo "❌ Failed to copy API client library\n";
    echo "   Source: $client_source\n";
    echo "   Destination: $client_dest\n";
    exit(1);
}
echo "✅ Copied API client library\n";

// Step 3: Create configuration file
$config_content = <<<PHP
<?php
/**
 * Intelligence API Configuration
 * 
 * Auto-generated by deployment script
 * Generated: {date('Y-m-d H:i:s')}
 */

define('INTELLIGENCE_API_KEY', '$api_key');
define('INTELLIGENCE_API_URL', 'https://gpt.ecigdis.co.nz/api/intelligence');
define('SERVER_ID', '$server');
define('SERVER_NAME', '{$config['name']}');

// Include API client
require_once __DIR__ . '/IntelligenceAPIClient.php';

// Create global client instance
\$GLOBALS['intelligence_client'] = new IntelligenceAPIClient(INTELLIGENCE_API_KEY);
\$GLOBALS['intelligence_bot'] = new IntelligenceBotCommands(INTELLIGENCE_API_KEY);

PHP;

if (!file_put_contents($kb_dir . '/config.php', $config_content)) {
    echo "❌ Failed to create configuration file\n";
    exit(1);
}
echo "✅ Created configuration file\n";

// Step 4: Create bot interface
$bot_interface = <<<'PHP'
<?php
/**
 * Intelligence Bot Interface
 * 
 * Simple web interface for bot commands
 */

require_once __DIR__ . '/config.php';

// Handle command
$response = '';
if (isset($_POST['command'])) {
    $command = $_POST['command'];
    $response = $GLOBALS['intelligence_bot']->handleCommand($command);
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Intelligence Bot - <?php echo SERVER_NAME; ?></title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
        }
        .header {
            background: white;
            padding: 30px;
            border-radius: 10px 10px 0 0;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header h1 {
            color: #333;
            margin-bottom: 10px;
        }
        .header p {
            color: #666;
        }
        .command-panel {
            background: #f8f9fa;
            padding: 30px;
            border-radius: 0 0 10px 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .input-group {
            display: flex;
            gap: 10px;
            margin-bottom: 20px;
        }
        input[type="text"] {
            flex: 1;
            padding: 15px;
            border: 2px solid #ddd;
            border-radius: 5px;
            font-size: 16px;
            font-family: 'Courier New', monospace;
        }
        button {
            padding: 15px 30px;
            background: #667eea;
            color: white;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            transition: background 0.3s;
        }
        button:hover {
            background: #5568d3;
        }
        .examples {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 10px;
            margin-bottom: 20px;
        }
        .example-btn {
            padding: 10px;
            background: white;
            border: 2px solid #ddd;
            border-radius: 5px;
            cursor: pointer;
            text-align: center;
            transition: all 0.3s;
        }
        .example-btn:hover {
            border-color: #667eea;
            color: #667eea;
        }
        .response {
            background: #2d3748;
            color: #e2e8f0;
            padding: 20px;
            border-radius: 5px;
            font-family: 'Courier New', monospace;
            white-space: pre-wrap;
            max-height: 500px;
            overflow-y: auto;
            line-height: 1.6;
        }
        .help {
            margin-top: 20px;
            padding: 15px;
            background: white;
            border-radius: 5px;
            border-left: 4px solid #667eea;
        }
        .help h3 {
            color: #333;
            margin-bottom: 10px;
        }
        .help ul {
            list-style: none;
            padding-left: 0;
        }
        .help li {
            padding: 5px 0;
            color: #666;
        }
        .help code {
            background: #f1f5f9;
            padding: 2px 6px;
            border-radius: 3px;
            color: #667eea;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🧠 Intelligence Bot</h1>
            <p><?php echo SERVER_NAME; ?> - API-Powered Knowledge Access</p>
        </div>
        
        <div class="command-panel">
            <form method="POST">
                <div class="input-group">
                    <input type="text" 
                           name="command" 
                           id="commandInput"
                           placeholder="Enter command (e.g., !search neural scanner)"
                           value="<?php echo htmlspecialchars($_POST['command'] ?? ''); ?>"
                           autofocus>
                    <button type="submit">Execute</button>
                </div>
            </form>
            
            <div class="examples">
                <div class="example-btn" onclick="setCommand('!search neural')">!search</div>
                <div class="example-btn" onclick="setCommand('!doc README.md')">!doc</div>
                <div class="example-btn" onclick="setCommand('!tree documentation')">!tree</div>
                <div class="example-btn" onclick="setCommand('!stats')">!stats</div>
            </div>
            
            <?php if ($response): ?>
            <div class="response"><?php echo htmlspecialchars($response); ?></div>
            <?php endif; ?>
            
            <div class="help">
                <h3>Available Commands</h3>
                <ul>
                    <li><code>!search keyword</code> - Search all centralized intelligence</li>
                    <li><code>!doc filename</code> - Retrieve specific document</li>
                    <li><code>!tree [path]</code> - Browse directory structure</li>
                    <li><code>!stats</code> - View system statistics</li>
                </ul>
            </div>
        </div>
    </div>
    
    <script>
        function setCommand(cmd) {
            document.getElementById('commandInput').value = cmd;
            document.getElementById('commandInput').focus();
        }
    </script>
</body>
</html>
PHP;

if (!file_put_contents($kb_dir . '/bot.php', $bot_interface)) {
    echo "❌ Failed to create bot interface\n";
    exit(1);
}
echo "✅ Created bot interface\n";

// Step 5: Create search interface
$search_interface = <<<'PHP'
<?php
/**
 * Intelligence Search Interface
 * 
 * Simple search interface for intelligence
 */

require_once __DIR__ . '/config.php';

$results = [];
if (isset($_GET['q'])) {
    $query = $_GET['q'];
    $response = $GLOBALS['intelligence_client']->search($query);
    if ($response['success']) {
        $results = $response['data']['results'];
    }
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Intelligence Search - <?php echo SERVER_NAME; ?></title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #f8f9fa;
            padding: 20px;
        }
        .container {
            max-width: 1000px;
            margin: 0 auto;
        }
        .search-box {
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            margin-bottom: 30px;
        }
        .search-box h1 {
            margin-bottom: 20px;
            color: #333;
        }
        .search-input {
            display: flex;
            gap: 10px;
        }
        input[type="text"] {
            flex: 1;
            padding: 15px;
            border: 2px solid #ddd;
            border-radius: 5px;
            font-size: 16px;
        }
        button {
            padding: 15px 30px;
            background: #667eea;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .result {
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            margin-bottom: 15px;
        }
        .result h3 {
            color: #333;
            margin-bottom: 10px;
        }
        .result-meta {
            color: #666;
            font-size: 14px;
            margin-bottom: 10px;
        }
        .tag {
            display: inline-block;
            padding: 3px 8px;
            background: #e0e7ff;
            color: #667eea;
            border-radius: 3px;
            font-size: 12px;
            margin-right: 5px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="search-box">
            <h1>🔍 Intelligence Search</h1>
            <form method="GET" class="search-input">
                <input type="text" 
                       name="q" 
                       placeholder="Search documentation, code, business intelligence..." 
                       value="<?php echo htmlspecialchars($_GET['q'] ?? ''); ?>"
                       autofocus>
                <button type="submit">Search</button>
            </form>
        </div>
        
        <?php if (!empty($results)): ?>
            <p><strong>Found <?php echo count($results); ?> results</strong></p>
            <?php foreach ($results as $result): ?>
            <div class="result">
                <h3>📄 <?php echo htmlspecialchars($result['filename']); ?></h3>
                <div class="result-meta">
                    <span class="tag"><?php echo $result['category']; ?></span>
                    <span class="tag"><?php echo $result['source_server']; ?></span>
                    <span><?php echo $result['path']; ?></span>
                </div>
            </div>
            <?php endforeach; ?>
        <?php elseif (isset($_GET['q'])): ?>
            <div class="result">
                <p>No results found for "<?php echo htmlspecialchars($_GET['q']); ?>"</p>
            </div>
        <?php endif; ?>
    </div>
</body>
</html>
PHP;

if (!file_put_contents($kb_dir . '/search.php', $search_interface)) {
    echo "❌ Failed to create search interface\n";
    exit(1);
}
echo "✅ Created search interface\n";

// Step 6: Create README
$readme_content = <<<MD
# 📚 Intelligence API Client - {$config['name']}

Lightweight knowledge base folder with API access to centralized intelligence.

## 🚀 Quick Access

- **Bot Interface**: [/_kb/bot.php](/_kb/bot.php)
- **Search Interface**: [/_kb/search.php](/_kb/search.php)
- **API Documentation**: https://gpt.ecigdis.co.nz/api/intelligence/

## 🤖 Bot Commands

Use these commands in bot.php or integrate into your AI interface:

- `!search keyword` - Search all documentation
- `!doc filename` - Retrieve specific document
- `!tree [path]` - Browse directory structure  
- `!stats` - View system statistics

## 📡 API Integration

```php
// Include API client
require_once __DIR__ . '/_kb/config.php';

// Search intelligence
\$results = \$GLOBALS['intelligence_client']->search('neural scanner');

// Get document
\$doc = \$GLOBALS['intelligence_client']->getDocument('documentation/jcepnzzkmj/README.md');

// Browse directory
\$tree = \$GLOBALS['intelligence_client']->getTree('documentation');

// Get statistics
\$stats = \$GLOBALS['intelligence_client']->getStats();
```

## 🔑 Configuration

- **Server**: {$config['name']} ($server)
- **API Key**: `$api_key`
- **API Endpoint**: https://gpt.ecigdis.co.nz/api/intelligence/

## 📖 Files

- `config.php` - API configuration
- `IntelligenceAPIClient.php` - API client library
- `bot.php` - Bot command interface
- `search.php` - Search interface
- `README.md` - This file

---
*Deployed: {date('Y-m-d H:i:s')}*
*Intelligence System v1.0.0*
MD;

if (!file_put_contents($kb_dir . '/README.md', $readme_content)) {
    echo "❌ Failed to create README\n";
    exit(1);
}
echo "✅ Created README\n";

// Step 7: Test API connection
echo "\n🧪 Testing API connection...\n";

require_once $client_dest;
$test_client = new IntelligenceAPIClient($api_key);

$test_result = $test_client->getStats();
if ($test_result['success']) {
    echo "✅ API connection successful!\n";
    echo "   Total files: {$test_result['data']['total_files']}\n";
    echo "   Client name: {$test_result['data']['client_name']}\n";
} else {
    echo "❌ API connection failed: {$test_result['error']['message']}\n";
}

echo "\n" . str_repeat('=', 60) . "\n";
echo "✅ DEPLOYMENT COMPLETE\n";
echo str_repeat('=', 60) . "\n\n";
echo "🎉 Intelligence API Client deployed successfully!\n\n";
echo "Next steps:\n";
echo "  1. Visit: https://{$config['domain']}/_kb/bot.php\n";
echo "  2. Try command: !search neural\n";
echo "  3. Browse: https://{$config['domain']}/_kb/search.php\n";
echo "  4. Integrate into your application using config.php\n\n";
